# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[[hexl]]
version = "1.2.5"
name = "1.2.5"
export_install_dir = "install"
fetch = "git clone https://github.com/intel/hexl.git --branch v%version%"
pre-build = """cmake -S %init_fetch_dir%/hexl -B %init_build_dir%
               -DCMAKE_INSTALL_PREFIX=%export_install_dir%"""
build = "cmake --build %init_build_dir% -j"
install = "cmake --install %init_install_dir%"
export_cmake = "install/lib/cmake/hexl-%version%"


[[ntl]]
version = "11.5.1"
name = "11.5.1"
init_pre_build_dir = "build"
init_build_dir = "build/ntl-%version%/src"
init_install_dir = "build/ntl-%version%/src"
export_install_dir = "install"
fetch = "wget https://libntl.org/ntl-%version%.tar.gz"
post-fetch = "bash -c 'tar -xvf %init_fetch_dir%/ntl-%version%.tar.gz -C %init_pre_build_dir%'"
build = "bash -c './configure NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on TUNE=generic PREFIX=%export_install_dir% && make -j'"
install = "make install"


[[helib]]
version = "master"
name = "psi-io"
root = "%name%"
export_install_dir = "install"
fetch = "git clone https://github.com/helibproject/HElib.git --branch %version%"
pre-build = """cmake -S %init_fetch_dir%/HElib -B %init_build_dir%
               -DCMAKE_INSTALL_PREFIX=%export_install_dir%
               -DNTL_DIR=$%ntl%/export_install_dir$
               -DUSE_INTEL_HEXL=ON
               -DHEXL_DIR=$%hexl%/export_cmake$"""
build = "cmake --build %init_build_dir% -j"
install = "cmake --install %init_install_dir%"
export_cmake = "install/share/cmake/helib"
# Build the utils directory
post-install = """bash -c 'cmake -S %init_fetch_dir%/HElib/utils -B %init_fetch_dir%/HElib/utils/build \
                  -Dhelib_DIR=%export_cmake% \
                  && cmake --build %init_fetch_dir%/HElib/utils/build -j'"""
# Dependencies
ntl = "ntl/11.5.1"
hexl = "hexl/1.2.5"


[[gtest]]
name = "v1.12.1"
version = "1.12.1"
export_install_dir = "install"
fetch = "git clone https://github.com/google/googletest.git --branch release-%version%"
pre-build = """cmake -S %init_fetch_dir%/googletest -B %init_build_dir%
               -DCMAKE_INSTALL_PREFIX=%export_install_dir%
               -DBUILD_MOCK=OFF"""
build = "cmake --build %init_build_dir% -j"
install = "cmake --install %init_build_dir%"
export_cmake = "install/lib/cmake/GTest"


[[json]]
name = "nlohmann-json"
version = "v3.11.2"
fetch = "git clone https://github.com/nlohmann/json.git --branch %version%"
export_fetch = "fetch/json"


[[modern-cpp-kafka]]
name = "v2022.10.12"
version = "v2022.10.12"
fetch = "git clone https://github.com/morganstanley/modern-cpp-kafka --branch %version%"
export_include_dir = "fetch/modern-cpp-kafka/include"


[[librdkafka]]
name = "v1.9.2"
version = "v1.9.2"
init_pre_build_dir = "build"
init_build_dir = "build/librdkafka"
init_install_dir = "build/librdkafka"
export_install_dir = "install"
fetch = "git clone https://github.com/edenhill/librdkafka --branch %version%"
post-fetch = "cp -R %init_fetch_dir%/librdkafka %init_pre_build_dir%"
build = "bash -c './configure --prefix=%export_install_dir% && make -j'"
install = "make install"


[[psi]]
name = "configurable-psi"
src_dir = "!toolkit-path!/deployments/config_psi/psi"
pre-build = """cmake -S %src_dir% -B %init_build_dir%
               -Dhelib_DIR=$%helib%/export_cmake$
               -DKAFKA_INCLUDE=$%kafka%/export_include_dir$
               -DKAFKA_DIR=$%librdkafka%/export_install_dir$
               -DJSON_DIR=$%json%/export_fetch$/single_include
               -DENABLE_TESTS=ON
               -DGTest_DIR=$%gtest%/export_cmake$"""
build = "cmake --build %init_build_dir% -j"
# Dependencies
helib = "helib/psi-io"
gtest = "gtest/v1.12.1"
json = "json/nlohmann-json"
kafka = "modern-cpp-kafka/v2022.10.12"
librdkafka = "librdkafka/v1.9.2"
