# Copyright (C) 2020-2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

image: ubuntu:18.04

variables:
  http_proxy: http://10.7.211.16:911
  https_proxy: http://10.7.211.16:912
  no_proxy: docker:2375,docker:2376,intel.com,.intel.com,10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME

stages:
  - format
  - build
  - test
  - kernels

format:
  stage: format
  only:
    refs:
      - merge_requests
      - master
  script:
    - pre-commit run --all-files

build:
  stage: build
  only:
    refs:
      - merge_requests
      - master
  script:
    - whoami
    - echo $HOME
    - echo $GIT_CLONE_PATH
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd
    # Build repo
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10
    - make -j5 all

  artifacts:
    paths:
      - build/ext_palisade/src/ext_palisade-build/third-party/
      - build/ext_palisade/src/ext_palisade-build/lib/
      - build/ext_palisade/src/ext_palisade-build/bin/benchmark/
      - build/ext_seal/src/ext_seal-build/lib/
      - build/ext_seal/lib/
      - build/micro-kernels/micro-kernels-seal
      - build/micro-kernels/micro-kernels-palisade
      - build/sample-kernels/kernels/
      - build/sample-kernels/sample-kernels-seal
      - build/sample-kernels/sample-kernels-palisade
      - build/sample-kernels/test/
    expire_in: 1 day

test:
  stage: test
  only:
    refs:
      - merge_requests
      - master
  script:
    - ./build/sample-kernels/test/unit-test
  dependencies:
    - build

micro-kernels-palisade:
  stage: kernels
  only:
    refs:
      - merge_requests
      - master
  script:
    - ./build/micro-kernels/micro-kernels-palisade --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build

micro-kernels-seal:
  stage: kernels
  only:
    refs:
      - merge_requests
      - master
  script:
    - ./build/micro-kernels/micro-kernels-seal --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build

sample-kernels-palisade:
  stage: kernels
  only:
    refs:
      - merge_requests
      - master
  script:
    - ./build/sample-kernels/sample-kernels-palisade --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build

sample-kernels-seal:
  stage: kernels
  only:
    refs:
      - merge_requests
      - master
  script:
    - ./build/sample-kernels/sample-kernels-seal --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build

#############
# IceLake CI
#############
format-icelake:
  stage: format
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - pre-commit run --all-files

build-icelake:
  stage: build
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - whoami
    - echo $HOME
    - echo $GIT_CLONE_PATH
    - echo "Testing from branch:"
    - echo $CI_COMMIT_REF_NAME
    - pwd
    - which python3

    # Build repo
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=clang++-10 -DCMAKE_C_COMPILER=clang-10
    - make -j5 all

  artifacts:
    paths:
      - build/ext_palisade/src/ext_palisade-build/third-party/
      - build/ext_palisade/src/ext_palisade-build/lib/
      - build/ext_palisade/src/ext_palisade-build/bin/benchmark/
      - build/ext_seal/src/ext_seal-build/lib/
      - build/ext_seal/lib/
      - build/micro-kernels/micro-kernels-seal
      - build/micro-kernels/micro-kernels-palisade
      - build/sample-kernels/kernels/
      - build/sample-kernels/sample-kernels-seal
      - build/sample-kernels/sample-kernels-palisade
      - build/sample-kernels/test/
    expire_in: 1 day

test-icelake:
  stage: test
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - ./build/sample-kernels/test/unit-test
  dependencies:
    - build-icelake


micro-kernels-palisade-icelake:
  stage: kernels
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - ./build/micro-kernels/micro-kernels-palisade --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build-icelake

micro-kernels-seal-icelake:
  stage: kernels
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - ./build/micro-kernels/micro-kernels-seal --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build-icelake

sample-kernels-palisade-icelake:
  stage: kernels
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - ./build/sample-kernels/sample-kernels-palisade --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build-icelake

sample-kernels-seal-icelake:
  stage: kernels
  only:
    refs:
      - master
      - schedule
  tags:
    - ice-lake
  script:
    - ./build/sample-kernels/sample-kernels-seal --benchmark_out_format=json --benchmark_out="${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"

  artifacts:
      paths:
        - "${CI_JOB_NAME}_${CI_COMMIT_SHA}.json"
      expire_in: 5 yr
  dependencies:
    - build-icelake
