# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[[openFHE]]
version = "!openfhe_dev_version!"
name = "!openfhe_dev_version!"
export_install_dir = "install"
fetch = "git clone https://github.com/openfheorg/openfhe-development.git --branch %version%"
pre-build = """cmake -S %init_fetch_dir%/openfhe-development -B %init_build_dir%
               -DCMAKE_INSTALL_PREFIX=%export_install_dir%"""
build = "cmake --build %init_build_dir% -j"
install = "cmake --install %init_install_dir%"
